# Generated by Django 5.2.4 on 2025-07-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_audio_task_completed_task_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
