# Generated by Django 5.2.4 on 2025-07-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_project_assigned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='tracker.project'),
        ),
    ]
