# Generated by Django 5.2.4 on 2025-07-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_component_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
