# Generated by Django 5.2.4 on 2025-07-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_task_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
    ]
