# Generated by Django 5.2.4 on 2025-07-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='tasks/docs/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='tasks/audio/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tasks/videos/'),
        ),
    ]
