# Generated by Django 5.2.4 on 2025-07-25 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_task_document_alter_task_audio_alter_task_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="traveler_docs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.project",
                    ),
                ),
            ],
        ),
    ]
