# Generated by Django 5.2.4 on 2025-08-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_message_file_alter_message_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="project",
        ),
        migrations.RemoveField(
            model_name="task",
            name="component",
        ),
        migrations.AddField(
            model_name="component",
            name="projects",
            field=models.ManyToManyField(
                related_name="components", to="tracker.project"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="components",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="tracker.component"
            ),
        ),
    ]
