# Generated by Django 5.2.4 on 2025-08-02 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_remove_component_project_remove_task_component_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="due_date",
        ),
        migrations.AddField(
            model_name="reminder",
            name="reminder_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
